# Generated by Django 5.1.7 on 2025-03-30 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productcategory_alter_product_category_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductCategory',
            new_name='Category',
        ),
    ]
